//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13._12._21
{
    using System;
    using System.Collections.Generic;
    
    public partial class reader_ticket
    {
        public int id { get; set; }
        public int id_reader { get; set; }
        public int id_book { get; set; }
    
        public virtual book book { get; set; }
        public virtual reader reader { get; set; }
    }
}
